periscope.db.host=localhost
periscope.db.port=5432
periscope.db.name=periscope_db
periscope.db.user=postgres
periscope.db.password=periscope
periscope.db.slot=periscope_slot
periscope.db.publication=periscope_pub

periscope.kafka.bootstrap-servers=localhost:9092
periscope.kafka.acks=all
periscope.kafka.retries=3
periscope.kafka.topic-prefix=periscope
